name: Release

on:
  push:
    branches: [ master, v** ]

env:
  CARGO_TERM_COLOR: always

jobs:
  zip_assets:
    name: Zip and upload Trader assets folder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Zip assets folder
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'assets.zip'
        path: 'assets/'
    - name: Upload assets ZIP file
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        artifacts: "assets.zip"
        name: 'Assets_ZIP'
        replacesArtifacts: true
        allowUpdates: true

